student:
  age: 18
  name: "张三"
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/express?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: root
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
server:
  port: 82
  tomcat:
    uri-encoding: UTF-8
mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.star.vo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.star.mapper: debug
